id: 731b159074614f8e8c70cd45905209b0
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_171-The_Questions_of_an_Old_Lady-v1
  language: bo
  author: ''
  volume: {}
